### PR TITLE
Bibtex

### PR DESCRIPTION
**Pull request by Damian96**
* [This commit](https://github.com/jamiely/citethis/commit/1b61c8ae522feda22f3cb65dac544320a1ff24e9) only has the necessary changes for the BibText citation style
* [This commit](606b19b225988f899003bd64eff4aaa1808a1e02) fixes the `TypeError: Object` that I got whenever the `getSiteSpecific` function returned null

So if you want to just merge the Bibtex style, I suggest you rebase to the first commit ;).
Tried it in my Firefox Dev and it works :).

### CODE REVIEW

**Comment by jamiely** [comment]
Thanks Damian, can you give me a URL to test this on?

**Comment by jamiely** [comment]
Deleted my previous comment, it's been so long I forget what this extension does, lol.

**Comment by jamiely** [comment]
Closing in favor of #9

**Comment by Damian96** [comment]
Thanks jamie, I saw your comment(s).

**Pull request closed without merging**
